BoxLayout:
    orientation: 'vertical'
    padding:10
    spacing:10
    background_color:(0,0,0,1)

    BoxLayout:
        orientation:'horizontal'
        spacing:10

        TextInput:
            id: input_number
            text: '7'
            font_size: 50
            multiline: False
            background_color:(1,1,1,1)
            foreground_color:(0,0,0,1)

        Button:
            text: 'Square'
            font_size:48
            background_color:(0.2,0.2,0.2,1)
            on_press: app.handle_calculate(input_number.text)

        Label:
            id: output_label
            text:''
            font_size: 42
            color: (1,0.5,0.6,1)
    Label:
        text:'Enter a number and press "Square"'
        font_size:32
        color:(1,1,1,1)

